- packages/common/global-types/index.d.ts
- packages/common/global-types/kaltura-player/base-middleware.d.ts
- packages/common/global-types/kaltura-player/engine-decorator.d.ts
- packages/common/global-types/kaltura-player/kaltura-player.d.ts
See corresponding Kaltura live plugin  https://github.com/kaltura/playkit-js-kaltura-live/pull/7
> Chore(common): Webc 1626 move interface and base class to contrib

- packages/plugin/src/contrib-services.ts
- packages/ui/src/components/overlay-item-container/_overlay-item-container.scss
- packages/ui/src/components/overlay-item-container/index.ts
- packages/ui/src/components/overlay-item-container/overlay-item-container.tsx
- packages/ui/src/index.ts
- packages/ui/src/overlay-item-data.tsx
- packages/ui/src/overlay-item.tsx
- packages/ui/src/overlay-manager.tsx
> feat(ui): add overlay manager

- packages/common/global-types/kaltura-player/player.d.ts
added ```isLive: () => boolean;``` method
> chore(common): add typescript declaration for kaltura player

- packages/common/global-types/index.d.ts
- packages/common/global-types/polyfill.d.ts
- packages/common/src/index.ts
- packages/common/src/kaltura-live-services.ts
- packages/common/src/uuid.ts
pls advise, 
where should we place _getNumberStringUuid and _isNaN polyfill?
> fix(common): fix how we creat uuid for anonymous user (webc-1694)

- packages/common/global-types/kaltura-player/player-config.d.ts
- packages/common/global-types/kaltura-player/player.d.ts
See kaltura live push 
https://github.com/kaltura/playkit-js-kaltura-live/pull/31
> Fev 421 adding types

- packages/ui/src/components/banner/_banner.scss
#Note: 
1. It fixes 1 char cut at the end and not the full scenario mentioned at webc-1766.
2. webc-1766 flow doesn't reproduce.
3. Couldn't test this at IE at win 10 - need QA's pc/ laptop for that.
> fix(ui): fix banner layout (webc-1766)

- packages/common/global-types/kaltura-player/player.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-contrib/166)
> feat(common): add configuration

- packages/ui/src/local-content-utils.ts
- fixed issue with content downloading in IE and Edge browsers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-contrib/182)
> Reach2 786 ie edge download issue

- packages/common/src/object-utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-contrib/185)
> chore: set 'any' type for 'ObjectUtils.get' method

- package-lock.json
- packages/push-notifications/package-lock.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-contrib/192)
> Chore dependabot non breaking merges

- packages/common/global-types/kaltura-player/player.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-contrib/206)
> chore(ui): add TS types for Kaltura player

- packages/ui/src/local-content-utils.ts
"time since" method. It uses in Info plugin to display date/time since event happened.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-contrib/211)
> chore(ui): added timeSince method to local-content-utils

- packages/common/global-types/kaltura-player/kaltura-player.d.ts
- packages/plugin/src/contrib-services.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-contrib/238)
> Fev 510 reset contrib services

- packages/common/global-types/kaltura-player/kaltura-player.d.ts
- packages/ui/src/components/popover/popover.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-contrib/241)
> chore(ui): add getPlayer method to KalturaPlayer type

- packages/ui/src/components/popover/popover.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-contrib/244)
> chore(ui): add keyboards enum

- package-lock.json
- packages/common/src/uuid.ts
- packages/plugin/package-lock.json
- packages/push-notifications/package-lock.json
- packages/ui/package-lock.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-contrib/252)
> chore(ui): fixed uuid import

- package-lock.json
- packages/linkify/webpack.config.js
- packages/ui/webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-contrib/263)
> chore(ui): upgrade webpack config for new style-loader

- packages/ui/src/kitchen-sink-item-data.ts
- packages/ui/src/kitchen-sink-manager.tsx
- packages/ui/src/upper-bar-manager.tsx
Pass `isActive` property to child component and re-render upper-bar items after state of kitchen-sink changed (one of plugin activated\deactivated);
> FEV-796 - Player V7| |Navigation 2.1.0| - UI - Icons on the upper menu are not as designed

- packages/push-notifications/src/socket-wrapper.ts
subscription to web-socket data has the same `queueNameHash` and `queueKeyHash`.  It cause an issue when few plugins use the same data from web-sockets. Current PR fix the issue by keep `onMessage` callback from all subscriptions and execute them when web-socket event happened.
> fix(fev-856): trigger onMessage callback for each event subscription

- packages/plugin/src/core-plugin.ts
issue: if live media offline the `mediaLoad` hook triggered each time player tries load media. It cause issue of multiple subscriptions to MEDIA_LOADED event (plugin initialized multiple times);
solution: use player event listener instead of `mediaLoad` hook to avoid multiple subscriptions to MEDIA_LOADED event.
> fix(fev-647): use player event listener instead of event manager
